### ISSUE TITLE
no attribute 'OpenAQ'

### ISSUE THREAD

**Issue by jeremy-bertincourt** [dhhagan/py-openaq#19]
Hi,

I have Ubuntu 14.04 and I the library seems to have been installed correctly. 
When I use the 3 first lines to get the data, I have the following issue:
'module' object has no attribute 'OpenAQ'.

Thank you for your reply.
Best regards,
Jeremy

**Comment by dhhagan** [comment]
Hi @jeremy-bertincourt . Can you past your code, as well as the version of the library you are using? You can find the version either through `pip list` or via `openaq.__version__`

**Comment by jeremy-bertincourt** [comment]
Hi,
my code:
#!/usr/bin/python
import openaq
aqi = openaq.OpenAQ()

my version: 1.0.1

Thank you.

**Comment by dhhagan** [comment]
@jeremy-bertincourt Interesting..how did you install it? Via `pip`? Could you paste the traceback?

**Comment by jeremy-bertincourt** [comment]
Yes, I used pip.
Here is the traceback:

Traceback (most recent call last):
  File "openaq.py", line 3, in <module>
    import openaq
  File "/home/openaq.py", line 5, in <module>
    api = openaq.OpenAQ()
AttributeError: 'module' object has no attribute 'OpenAQ'

ᐧ

**Comment by dhhagan** [comment]
@jeremy-bertincourt Ahh..did you name your file openaq.py? Try changing that and see what happens..

**Comment by jeremy-bertincourt** [comment]
I changed the name of the file, and now it works :) I see, there was a
conflict with the names.
Thank you!
ᐧ
