### ISSUE TITLE
Helper function for unit conversion

### ISSUE THREAD

**Issue by dhhagan** [dhhagan/py-openaq#20]
Add a helper function to convert between ppb and ugm3 and viceversa for all common components (gases)

**Comment by wjrholden** [comment]
I would like to work on implementing this feature for you! :)
I was doing a little bit of preliminary research and it appears that the OpenAQ measurements for the gases SO2, NO2, O3, CO, and BC (which I assume is benzene?) all have well-described conversion factors. I'm curious how PM25 and PM10 might also be easily converted considering their unknown composition and therefore unknown molecular weight?

**Comment by dhhagan** [comment]
Hey @wjrholden Great to hear! BC is Black Carbon, which is a component of particulate matter. Hopefully, PM25 and PM10 don't need to be converted, as it is pretty standard to report them in units of mass (microgram-cm3). However, many locations throughout Asia and Europe report the gases in units of mass as well, rather than as mixing ratios (ppb, ppm). While there are complicated ways to calculate the mixing ratio based on pressures, temperatures, etc, it should be pretty easy to just use the ideal gas law and assume atmospheric conditions. In doing so, there should be conversion factors for each gas to switch between mass units and mixing ratios. Let me know if you have any questions! [This](http://acmg.seas.harvard.edu/people/faculty/djj/book/bookchap1.html#pgfId=439991) is a great resource as well.

**Comment by wjrholden** [comment]
Hey Dan, I've been super busy but I haven't forgotten about implementing this for ya! Things are finally settling down though and I should have time to work on it soon. Sorry for the delay. -William
