### ISSUE TITLE
Deal with IP-based rate limiting

### ISSUE THREAD

**Issue by dhhagan** [dhhagan/py-openaq#22]
It doesn't appear that rate-limit info is included in the headers for some reason, so figure out which error code is associated with a timeout?

**Comment by jflasher** [comment]
If `openaq-api` is the rate limiter, it should be returning a `429` error code.

**Comment by dhhagan** [comment]
What else would be the rate limiter? Also, is there a reason that the Rate Limiting stats are pushed through in the headers?

**Comment by jflasher** [comment]
From the `openaq-api` side, nothing else would be the rate limiter, but I wasn't positive if that's what this issue was referencing. We're using https://aws.amazon.com/waf/ for the rate-limiting which does not currently add information to the headers.
