### ISSUE TITLE
`date_from` and `date_to` having no effect 

### ISSUE THREAD

**Issue by nipunbatra** [dhhagan/py-openaq#24]
```python
import matplotlib.pyplot as plt
import seaborn as sns
import openaq


api = openaq.OpenAQ()

# grab the data
res = api.measurements(city='Delhi', parameter='pm25', limit=10000, df=True, date_from='2018-01-01' )

res.sort_index(inplace=True)
```

`res` only has data from today till `limit` points going back in date. What I was looking was to download date from start to end. I thought that `date_from` and `date_to` in `.measurements` would take care of that.

Am I doing it correctly?

**Comment by dhhagan** [comment]
Hey @nipunbatra you are using it correctly; however, a little while ago OpenAQ began moving "old" data to an external datastore and thus you can only access something like the last 90 days of data (not sure on the exact length) via the API. Could you try running it for, say, May 1 - May 7 and see what you get?
