### ISSUE TITLE
Add standards to plot

### ISSUE THREAD

**Issue by sergiolucero** [dhhagan/py-openaq#26]
The plotting abilities are very useful but it would be nice to be able to add a reference. For every given country and pollutant, there is a standard for (daily/hourly) averages. How can we add this to the plot inside dateplot?

    def dateplot(y, **kwargs):
        ax = plt.gca()
        data = kwargs.pop("data")
        rs = kwargs.pop("rs", '12h')
        data.resample(rs).mean().plot(y=y, ax=ax, grid=False, **kwargs)

g = sns.FacetGrid(df, col='parameter', col_wrap=3, size=4, hue='parameter', sharey=False)
g.map_dataframe(dateplot, "corrected", rs='12h')

**Comment by dhhagan** [comment]
I'm not sure if I 100% understand what you mean here. Are you referring to a horizontal line at some value for something like the WHO standard for the pollutant?

**Comment by sergiolucero** [comment]
Yes, precisely that!

**Comment by dhhagan** [comment]
Ahh okay. Well, if you are plotting on a `FacetGrid` as we are in this example, you can add a horizontal line on each plot with:

    def dateplot(y, **kwargs):
        ax = plt.gca()
        ax.axhline(y=<value>)
        ...

In fact, any matplotlib methods will work, as this (`seaborn`) is just a wrapper around matplotlib. More info on this method [here](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.axhline.html).

**Comment by sergiolucero** [comment]
That is brilliant! I will share what I'm doing with this in a few hours. We
are currently experiencing a national air quality crisis in Chile.
