### ISSUE TITLE
Is filtering actually working in this API?

### ISSUE THREAD

**Issue by PCaff** [dhhagan/py-openaq#29]
Here is a simple example. All it does is return a 504 Bad Request Error.

`>>> import openaq
>>> opaq = openaq.OpenAQ()
>>> status, resp = opaq.measurements(country='US')
`

I copied the examples in the code. Am i doing something wrong?

**Comment by dhhagan** [comment]
Nope - that should work just fine. I just tried using httpie and it threw a timeout error (504). It appears there is something wrong with the OpenAQ API itself. @jflasher any idea if there are reported issues with the API? Did something change recently that I'm not aware of?

**Comment by jflasher** [comment]
Nope, nothing out of the ordinary. We've been seeing semi-frequent timeouts for large, unscoped queries though. If you add more parameters to the query to lower the result set, you should have more success. Note that we have a large PR in the works that should alleviate this.
