### ISSUE TITLE
Issue with pulling api city names 

### ISSUE THREAD

**Issue by als0076** [dhhagan/py-openaq#32]
When api.cities is used to pull cities for a country (say India), the name of the country also appear on the list of cities.  Also some of the strings for city names has "\n" within the string.  Would it be possible to fix this?

**Comment by dhhagan** [comment]
Hey @als0076 - thanks for pointing this out. This appears to be an issue with the OpenAQ API itself, not the python wrapper, so it may be a good idea to open an issue on that repository instead.

**Comment by als0076** [comment]
@dhhagan okay I will do. Thanks for responding so quickly!
