### ISSUE TITLE
Not possible to get measurements from sensors with undefined cities?

### ISSUE THREAD

**Issue by GeorgeCodeHub** [dhhagan/py-openaq#34]
Hello there,

Thank you for the amazing tool and great documentation.

I would like to ask though if it is possible to get data from sensors that have undefined cities. 

For example, in Greece, if I execute the following line:

```
res = openaq.measurements(coordinates="38.00684829,23.73353293",
                          radius=20000,
                          limit=100000, 
                          parameter="pm10", 
                          df=True, 
                          sort="asc")
```

I get these sensors: 
'GR0038A', 'GR0035A', 'GR0031A', 'GR0022A', 'GR0030A', 'GR0028A', 'GR0037A', 'GR0039A', 'GR0120A', 'GR0003A'

However, if I try to get all the sensors near the same coordinates:

```
res = openaq.locations(coordinates="38.00684829,23.73353293",
                      radius=20000,
                      limit=100000, 
                      parameter="pm10", 
                      df=True, 
                      sort="asc")
```

I get the following sensors:
'CleanAir in Greece - Thiseio', 'PANACEA_002', 'PANACEA_AirPaP_008', 'ATH-ENVICARE-3', 'PANACEA_007', 'PANACEA_003', 'Ano Liosia (Perneri)', 'ATHENS_02', 'National Technical University of Athens', 'PANACEA_AirPaP_002', 'PANACEA_004', 'PPCITY11', 'PANACEA_AirPaP_006', 'PANACEA_AirPaP_001', 'PANACEA_022', 'ATH-ENVICARE-0', 'PANACEA_000', 'PANACEA_001', 'ATH-ENVICARE-1', 'PANACEA_020', 'PPCITY12', 'PANACEA_014', 'ATH-ENVICARE-4', 'ATH-ENVICARE-2', 'PPCITY21', 'PANACEA_AirPaP_007', 'PANACEA_005', 'PANACEA_021', 'GR0120A', 'GR0037A', 'GR0039A', 'GR0038A', 'GR0035A', 'GR0031A', 'GR0030A', 'GR0028A', 'GR0022A', 'ATH-ENVICARE-6', 'GR0003A', 'PANACEA_AirPaP_004', 'PANACEA_019', 'PANACEA_AirPaP_005', 'ATH-ENVICARE-5', 'PPCITY16', 'Exarcheia, Athens, Greece'

I looked in the data and noticed that the missing sensors have their city as NaN

Is there a way to get these sensors when calling for measurements?

**Comment by dhhagan** [comment]
Hi @GeorgeCodeHub - that's a great question! I don't think I can personally answer it. I would recommend re-posting it on the OpenAQ API repository since this library just wraps that one.

https://github.com/openaq/openaq-api

**Comment by GeorgeCodeHub** [comment]
Thank you for the quick response! I will respond here if I find a solution to the issue.
