### ISSUE TITLE
`from pandas.io.json import json_normalize` should be changed to `from pandas import json_normalize`

### ISSUE THREAD

**Issue by douseful** [dhhagan/py-openaq#43]
`ImportError: cannot import name 'json_normalize' from 'pandas.io.json'` 
[seems this api had changed. ](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.json_normalize.html)
<img width="775" alt="image" src="https://github.com/dhhagan/py-openaq/assets/52767905/ffced416-cd5f-4214-969c-c22b88bfd04e">

<img width="850" alt="image" src="https://github.com/dhhagan/py-openaq/assets/52767905/a45317c3-50cc-4f4d-849f-07f1ce63c31d">

**Comment by dhhagan** [comment]
Hi @douseful - it looks like you're using a version of `pandas` that is substantially newer than what existed when this library was last maintained. My understanding is that OpenAQ is developing and will be releasing their own python API wrapper, so I have stopped maintaining this version. I don't really have the capacity to make changes at this time, but am happy to welcome PRs which I can review and approve.
